// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    region: 'us-west-2',
    userPoolId: 'us-west-2_1TIwMeuxI',
    userPoolWebClientId: '5b3ctsv3lm742cgt8fv7bq7nnh'
};

export default awsmobile;
